image: dydokamil/godot-ci:latest

stages:
  - tests

unitTests:
  stage: tests
  script:
    - godot -s addons/gut/gut_cmdln.gd -d --path $PWD -ginclude_subdirs -gdir=res://tests -gexit -gprefix=test_

